monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: debug
            handler: nested
            #            excluded_http_codes: [404, 405]
        nested:
            type: stream
            path: "%kernel.logs_dir%/dev18.log"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
